name: Mirror to Gitee Repo

on:
  push:
  schedule:
    - cron: "1 17 * * *"

jobs:
  run:
    name: Sync GitHub to Gitee
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://github.com/truecharts/catalog.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "https://zhouu:${{ secrets.GITEE_TOKEN }}@gitee.com/zhouu/truecharts.git"
          destination_branch: "refs/heads/*"
