name: Mirror Repo to Gitee

on:
  schedule:
    - cron: "1 17 * * *" # 设置定时任务，中国时间凌晨1点进行同步
  workflow_dispatch: # 手动触发构建

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://github.com/truecharts/catalog.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "https://zhouu:${{ secrets.GITEE_TOKEN }}@gitee.com/zhouu/truecharts.git"
          destination_branch: "refs/heads/*"
